# Generated by Django 4.0.2 on 2022-03-01 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_alter_garage_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('C', 'Carro'), ('M', 'Moto')], max_length=1)),
                ('model', models.CharField(max_length=254)),
                ('color', models.CharField(max_length=254)),
                ('garage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='garage', to='garage.garage')),
            ],
        ),
    ]
