# Generated by Django 4.0.2 on 2022-03-02 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0004_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='garage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garage', to='garage.garage'),
        ),
    ]
