# Generated by Django 4.0.2 on 2022-02-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_newuser_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='password2',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
